name: ARGEconomy
main: biz.argirc.Magick.ARGEconomy.ARGEcon
version: 1.0.0
author: Magick
description: >
            ARG! Economy
commands:
  store:
    description: List items available in the store
    usage: |
           /<command> - Lists items available for purchase.
           
  buy:
    description: List items available in the store
    usage: |
           /<command>  diamondpick - Purchase a Diamond Pick-axe from the store
  bank:
    description: Get your currency total
    usage: |
           /<command> - Check your currency balance