name: ARGAntiPirate
main: com.bukkit.Magick.ARGAntiPirate.ARGAntiPirate
version: 1.0.1
author: Magick
description: >
            ARG! Anti Chest Pirate and general guest protection
commands:
  adduser:
    description: Assign a numeric group ID to the player
    usage: |
           /<command> [player] [groupID]
           Example: /<command> [player] [groupID] - Add player to group.
  unlock:
    description: Unlock a chest
    usage: |
           /<command> 
           Example: /<command> - Unlock Chest
  argreload:
    description: reload chest and rank data
    usage: |
           /<command> 
           Example: /<command> - reload chest and rank data
  argsave:
    description: save chest and rank data
    usage: |
           /<command> 
           Example: /<command> -save chest and rank data
  removeplayer:
    description: remove player from ranks
    usage: |
           /<command> 
           Example: /<command> -remove player from ranks
  globalprotect:
    description: toggle global world protect true/false
    usage: |
           /<command>
           Example: /<command> true - turns global world protection on