name: ARG MagickMod
main: biz.argirc.Minecraft.MagickMod
version: 1.6
author: Magick
database: true
description: >
            ARG! MagickMod - Custom plugin for ARG-IRC Minecraft server
commands:
  unlock:
    description: Unlock the chest you are targeting
    usage: |
           /<command> 
           Example: /<command>
  chestcount:
    description: Shows number of chests owned by specified user
    usage: |
           /<command>
           Example: /<command> user11 - shows number of chests user owns
  chesthelp:
    description: Shows help
    usage: |
           /<command>
           Example: /<command>
  setrank:
    description: Set a users rank
    usage: |
           /<command>
           Example: /<command> UserGuyBob 1 - set userGuyBob to rank 1
  setcompass:
    description: Set your compass to your current location
    usage: |
           /<command> - Set your compass to your current location         
  who:
    description: Display players online
    usage: |
           /<command> - Display players online
  spawnmob:
    description: Spawn a mob (ops only)
    usage: |
           /<command> - <mobtype> <count> - Spawn <count> number of <mobtype> where you are pointing
  setserverspawn:
    description: Set spawn point (ops only)
    usage: |
           /<command> - Allows an op to set server spawn point to their location.
  teleport:
    description: Teleport to location you are pointing at
    usage: |
           /<command> - Teleport to the location you are pointing at
  xyzport:
    description: Teleport to location x y z (ops only)
    usage: |
           /<command> - Teleport to the location at x y z (safely?)
  killhostile:
    description: Kill all hostile mobs on map. (ops only)
    usage: |
           /<command> - Kills all hostile mobs on map.
  killfriendly:
    description: Kill all friendly mobs on map. (except wolves?) (ops only)
    usage: |
           /<command> - Kills all animals on map.