name: ARG MagickMod
main: biz.argirc.Minecraft.MagickMod
version: 2.0
author: Magick
database: true
description: >
            ARG! MagickMod - Custom plugin for ARG-IRC Minecraft server
commands:
  unlock:
    description: Unlock the chest you are targeting
    usage: |
           /<command> 
           Example: /<command>
  chestcount:
    description: Shows number of chests owned by specified user
    usage: |
           /<command>
           Example: /<command> user11 - shows number of chests user owns
  chesthelp:
    description: Shows help
    usage: |
           /<command>
           Example: /<command>
  setrank:
    description: Set a users rank
    usage: |
           /<command>
           Example: /<command> UserGuyBob 1 - set userGuyBob to rank 1
  setcompass:
    description: Set your compass to your current location
    usage: |
           /<command> - Set your compass to your current location         
  who:
    description: Display players online
    usage: |
           /<command> - Display players online
  spawnmob:
    description: Spawn a mob (ops only)
    usage: |
           /<command> - <mobtype> <count> - Spawn <count> number of <mobtype> where you are pointing
  setserverspawn:
    description: Set spawn point (ops only)
    usage: |
           /<command> - Allows an op to set server spawn point to their location.
  teleport:
    description: Teleport to location you are pointing at
    usage: |
           /<command> - Teleport to the location you are pointing at
  xyzport:
    description: Teleport to location x y z (ops only)
    usage: |
           /<command> - Teleport to the location at x y z (safely?)
  killhostile:
    description: Kill all hostile mobs on map. (ops only)
    usage: |
           /<command> - Kills all hostile mobs on map.
  killfriendly:
    description: Kill all friendly mobs on map. (except wolves?) (ops only)
    usage: |
           /<command> - Kills all animals on map.
  challenge:
    description: Challenge player(s) to an Arena battle
    usage: |
           /<command> - CHALLENGE!
  wallchunk:
    description: Create a wall around the current chunk
    usage: |
           /<command> - wall the current chunk
  store:
    description: List items for sale at Item Shop
    usage: |
           /<command> - List items and their cost
  buy:
    description: Buy an item from the store
    usage: |
           /<command> - Buy item
  die:
    description: Random death!
    usage: |
           /<command> - DIE!!!
  bank:
    description: Get your account balance
    usage: |
           /<command> - show balance
  regenchunk:
    description: Regenerate the chunk you are in
    usage: |
           /<command> - Regenerate the chunk you are in
  givetrack:
    description: Give player X stacks of track
    usage: |
           /<command> magicksid 5 - give magicksid 5 stacks of track
  makecarttunnel:
    description: Create a minecart tunnel
    usage: |
           /<command>
  direction:
    description: Get the direction you are facing
    usage: |
           /<command>
  restoreinventory:
    description: restore player inventory
    usage: |
           /<command>