name: ARG MagickMod
main: biz.argirc.Minecraft.MagickMod
version: 1.5.5
author: Magick
database: true
description: >
            ARG! Anti Chest Pirate and chest
commands:
  unlock:
    description: Unlock the chest you are targeting
    usage: |
           /<command> 
           Example: /<command>
  chestcount:
    description: Shows number of chests owned by specified user
    usage: |
           /<command>
           Example: /<command> user11 - shows number of chests user owns
  chesthelp:
    description: Shows help
    usage: |
           /<command>
           Example: /<command>