name: ARGUtilities
main: com.bukkit.Magick.ARGUtilities.ARGUtilities
version: 1.0.0
author: Magick
description: >
            ARG! Utilities
commands:
  setcompass:
    description: Set your compass to your current location
    usage: |
           /<command> - Set your compass to your current location         
  who:
    description: Display players online
    usage: |
           /<command> - Display players online
  spawnmob:
    description: Spawn a mob (ops only)
    usage: |
           /<command> - <mobtype> <count> - Spawn <count> nnumber of <mobtype> where you are pointing
  setspawn:
    description: Set spawn point (ops only)
    usage: |
           /<command> - Allows an op to set spawn point to their location.
  teleport:
    description: Teleport to location you are pointing at
    usage: |
           /<command> - Teleport to the location you are pointing at
  explode:
    description: Make yourself explode.
    usage: |
           /<command> - KABOOM!
  xyzport:
    description: Teleport to location x y z (ops only)
    usage: |
           /<command> - Teleport to the location at x y z (safely?)
  killallmobs:
    description: Kill all hostile mobs on map. (ops only)
    usage: |
           /<command> - Kills all hostile mobs on map.
  killallanimals:
    description: Kill all mobs on map. (ops only)
    usage: |
           /<command> - Kills all animals on map.